"""add_explanation_and_metadata

Revision ID: 026643869f33
Revises: c99453ba5d49
Create Date: 2026-06-05 15:47:48.465825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026643869f33'
down_revision = 'c99453ba5d49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('explanation', sa.JSON(), nullable=True))
    op.add_column('decisions', sa.Column('execution_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'execution_metadata')
    op.drop_column('decisions', 'explanation')
    # ### end Alembic commands ###
