"""init_postgres

Revision ID: c99453ba5d49
Revises: b77618c6f6ac
Create Date: 2026-06-05 15:40:13.753572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99453ba5d49'
down_revision = 'b77618c6f6ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
