"""Add Policy and PolicyVersion tables

Revision ID: cd04945cb0f1
Revises: 026643869f33
Create Date: 2026-06-05 20:52:51.745463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd04945cb0f1'
down_revision = '026643869f33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_policies_decision_type'), 'policies', ['decision_type'], unique=False)
    op.create_table('policy_versions',
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_policies_decision_type'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
